networks:
  app-tool:
    driver: bridge

services:

  zipkin:
    container_name: zipkin-server
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    networks:
      - app-tool

  eureka:
    container_name: eureka-server
    build:
      context: eureka-server
      dockerfile: Dockerfile
    restart: always
    ports:
      - 2000:2000
    networks:
      - app-tool

  gateway:
    container_name: api-gateway
    build:
      context: api-gateway
      dockerfile: Dockerfile
    restart: always

    ports:
      - 8080:8080

    depends_on:
      - add-service
      - get-service

    networks:
      - app-tool

  add-service:
    container_name: add-service
    build:
      context: add-service
      dockerfile: Dockerfile
    restart: always
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - MANAGEMENT.ZIPKIN.TRACING.ENDPOINT=http://zipkin-server:9411/api/v2/spans

    depends_on:
      - kafka
      - eureka

    networks:
      - app-tool

  get-service:
    container_name: get-service
    build:
      context: get-service
      dockerfile: Dockerfile
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/people
      - SPRING_DATASOURCE_USERNAME=alex
      - SPRING_DATASOURCE_PASSWORD=alex
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - MANAGEMENT.ZIPKIN.TRACING.ENDPOINT=http://zipkin-server:9411/api/v2/spans
    depends_on:
      - db
      - kafka
      - eureka

    networks:
      - app-tool

  db:
    container_name: db
    image: postgres:latest
    environment:
      - POSTGRES_USER=alex
      - POSTGRES_PASSWORD=alex
      - POSTGRES_DB=people
    ports:
      - 5432:5432
    volumes:
      - D:\volume:/var/lib/postgresql/data

    networks:
      - app-tool

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
    depends_on:
      - db

    networks:
      - app-tool

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

    networks:
      - app-tool

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 3

    networks:
      - app-tool

    depends_on:
      - zookeeper
