server:
  port: 0

spring:
  application:
    name: get-service

#  datasource:
#    url: jdbc:postgresql://localhost:5432/people
#    username: alex
#    password: alex
#    driver-class-name: org.postgresql.Driver

  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.example.microservicereciever.serializers.PersonDeserializer

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: com.example.microservicereciever.serializers.PersonSerializer

eureka:
  client:
    service-url:
      defaultZone: http://eureka:2000/eureka

management:
  tracing:
    sampling:
      probability: 1