server:
  port: 0

spring:
  application:
    name: get-service
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/people
    username: alex
    password: alex
    driver-class-name: org.postgresql.Driver

  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.example.getservice.serializers.PersonDeserializer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:2000/eureka

management:
  tracing:
    sampling:
      probability: 1